Add ESLint
flarum/gulp pull request #3
Opened 2016-10-18 10:44 UTC by dav-is

Added Eslint. Rules still need some discussion

2016-10-18 21:11 UTC, franzliedke requested changes
Please fix these minor formatting issues and then squash all your commits together.

2016-10-18 21:11 UTC, franzliedke commented on index.js
> +var gulpTap = require("gulp-tap");
Please use single quotes here for consistency.

2016-10-18 21:11 UTC, franzliedke commented on index.js
> +function isFixed (file) {
Please remove the space before the opening parenthesis.

2016-10-18 21:11 UTC, franzliedke commented on package.json
> +      }]
Can you explain what all of these do? Especially the `order` array isn't particularly self-explanatory.

2016-10-18 21:12 UTC, franzliedke commented
@tobscure You'll have to take care of this one.

2016-10-18 21:19 UTC, dav-is commented on package.json
> +      }]
The order is the order methods must come in classes. I looked for the most common pattern for methods and came up with this order. As for the rest, the documentation explains it better than I could.

2016-10-18 21:23 UTC, dav-is commented
One of the rules that I wasn't sure to turn on or off was defining methods as statics if they don't use `this`.

2018-12-12 20:45 UTC, franzliedke commented
This package is now obsolete, in favor of flarum-webpack-config, right? Let's archive this then... @tobscure

2018-12-13 01:17 UTC, closed without merging